const PATH_API_VIEW = '/api/view'; // корневой путь к эндпоинтам представлений
const PATH_API_ACTION = '/api/action'; // корневой путь к эндпоинтам действий

const HTTP_STATUS = {
    UNAUTHORIZED: 401
};

const SORT_DIR_ASC = 'asc';
const SORT_DIR_DESC = 'desc';

// Поля для табулятора
const TABR_FIELD = {
    ID: 'id',
    AGREEMENT_DATE: 'agreementDate',
    AMOUNT: 'amount',
    APPLICABILITY: 'applicability',
    APPROVAL_DATE: 'approvalDate',
    APPROVE_DATE: 'approveDate',
    APPROVED_BY: 'approvedBy',
    AGREED: 'agreed',
    AGREED_BY: 'agreedBy',
    MILITARY: 'military',
    MILITARY_BY: 'militaryBy',
    CHECKED: 'checked',
    CHECKED_BY: 'checkedBy',
    CHECKED_ON: 'checkedOn',
    DESIGNED: 'designed',
    DESIGNED_BY: 'designedBy',
    DESIGNED_ON: 'designedOn',
    METROLOGIST: 'metrologist',
    METROLOGIST_BY: 'metrologistBy',
    METROLOGIST_ON: 'metrologistOn',
    NORMOCONTROLLER: 'normocontroller',
    NORMOCONTROLLER_BY: 'normocontrollerBy',
    NORMOCONTROLLER_ON: 'normocontrollerOn',
    TECHNOLOGICAL_CHIEF: 'technologicalChief',
    TECHNOLOGICAL_CHIEF_BY: 'technologicalChiefBy',
    AGREED_TOOLTIP: 'agreedTooltip',
    MILITARY_TOOLTIP: 'militaryTooltip',
    CHECKED_TOOLTIP: 'checkedTooltip',
    DESIGNED_TOOLTIP: 'designedTooltip',
    METROLOGIST_TOOLTIP: 'metrologistTooltip',
    NORMOCONTROLLER_TOOLTIP: 'normocontrollerTooltip',
    TECHNOLOGICAL_CHIEF_TOOLTIP: 'technologicalChiefTooltip',
    COMMENT: 'comment',
    CREATE_DATE: 'createDate',
    CREATED_BY: 'createdBy',
    DESCRIPTION: 'description',
    DOC_NUMBER: 'docNumber',
    INTRODUCTION_INDICATION: 'introductionIndication',
    NOTIFICATION_NUMBER: 'notificationNumber',
    NUMBER_IN_YEAR: 'numberInYear',
    PARENT_NUMBER_IN_YEAR: 'parentNumberInYear',
    ENTITY_NUMBER: 'entityNumber',
    PRODUCT_NAME: 'productName',
    REASON: 'reason',
    RELEASE_ON: 'releaseOn',
    RESERVE_INDICATION: 'reserveIndication',
    SET_NUMBER: 'setNumber',
    TECH_USER: 'techUser',
    TP_TYPE: 'tpType',
    TERM_CHANGE_ON: 'termChangeOn',
    TYPE: 'type',
    FULL_NUMBER: 'fullNumber',
    CUSTOMER: 'customer',
    CITY: 'city',
    STATUS: 'status',
    NAME: 'name',
    ADDRESS: 'address',
    STRUCTURE: 'structure',
    IDENTIFIER: 'identifier',
    MANAGER: 'manager',
    SEND_TO_CLIENT_DATE: 'sendToClientDate',
    READINESS: 'readiness',
    START_ON: 'startOn',
    END_ON: 'endOn',
    VERSION: 'version',
    LAUNCHES: 'launches',
    DATE: 'date',
    CONTRACT_NUMBER: 'contractNumber',
    SUPPLIER_NAME: 'supplierName',
    PRICE: 'price',
    INITIAL_QUANTITY: 'initialQuantity',
    CURRENT_QUANTITY: 'currentQuantity',
    RESERVED_QUANTITY: 'reservedQuantity',
    WASTED_QUANTITY: 'wastedQuantity',
    NOT_ACCEPTED_QUANTITY: 'notAcceptedQuantity',
    CONTRACT_AMOUNT: 'contractAmount',
    RF_CONTRACT_AMOUNT: 'rfContractAmount',
    RF_ASSEMBLED_AMOUNT: 'rfAssembledAmount',
    UFRF_CONTRACT_AMOUNT: 'ufrfContractAmount',
    UFRF_ASSEMBLED_AMOUNT: 'ufrfAssembledAmount',
    UFRF_CONTRACT_IN_OTHER_PRODUCT_AMOUNT: 'ufrfContractInOtherProductAmount',
    RESERVE_AMOUNT: 'reserveAmount',
    USED_RESERVE_AMOUNT: 'usedReserveAmount',
    ASSEMBLED_AMOUNT: 'assembledAmount',
    ACCEPT_TYPE: 'acceptType',
    SPECIAL_TEST_TYPE: 'specialTestType',
    DELIVERY_DATE: 'deliveryDate',
    PRICE_KIND: 'priceKind',
    COST: 'cost',
    DECIMAL_NUMBER: 'decimalNumber',
    TYPE_NAME: 'typeName',
    PROTOCOL_NUMBER: 'protocolNumber',
    LAUNCH_AMOUNT: 'launchAmount',
    SHIPPED_AMOUNT: 'shippedAmount',
    ALLOTMENT_AMOUNT: 'allotmentAmount',
    PAID: 'paid',
    PERCENT_PAID: 'percentPaid',
    FINAL_PRICE: 'finalPrice',
    LAUNCH_NUMBER: 'launchNumber',
    LETTER_NUMBER: 'letterNumber',
    LETTER_CREATION_DATE: 'letterCreationDate',
    SHIPMENT_PERMIT_DATE: 'shipmentPermitDate',
    TRANSFER_FOR_WRAPPING_DATE: 'transferForWrappingDate',
    READY_FOR_SHIPMENT_DATE: 'readyForShipmentDate',
    TITLE: 'title',
    ACCOUNT: 'account',
    BANK_NAME: 'bankName',
    INVOICE_NUMBER: 'invoiceNumber',
    DATE_VALID_BEFORE: 'dateValidBefore',
    PAID_AMOUNT: 'paidAmount',
    STATUS_NAME: 'statusName',
    PAYMENT_NUMBER: 'paymentNumber',
    PAYMENT_DATE: 'paymentDate',
    PAYMENT_AMOUNT: 'paymentAmount',
    ADVANCE_INVOICE: 'advanceInvoice',
    FILE_HASH: 'fileHash',
    PREFIX: 'prefix',
    START_DATE: 'startDate',
    SEPARATE_DELIVERY: 'separateDelivery',
    NUMBER: 'number',
    CHARACTERISTIC: 'characteristic',
    CODE: 'code',
    SEPARATE_ACCOUNT: 'separateAccount',
    BANK_INFO: 'bankInfo',
    SECTION_INFO: 'sectionInfo',
    COMPANY: 'company',
    APPROVED: 'approved',
    PERIOD: 'period',
    PRICE_WO_PACK: 'priceWoPack',
    PRICE_PACK: 'pricePack',
    PRICE_PACK_RESEARCH: 'pricePackResearch',
    DOC_NAME: 'docName',
    ADDITIONAL_SALARY: 'additionalSalary',
    SOCIAL_INSURANCE: 'socialInsurance',
    OVERHEAD_COSTS: 'overheadCosts',
    PRODUCTION_COSTS: 'productionCosts',
    HOUSEHOLD_EXPENSES: 'householdExpenses',
    PRESENT_LOG_RECORD_NUMBER: 'presentLogRecordNumber',
    REGISTRATION_DATE: 'registrationDate',
    EXAM_ACT: 'examAct',
    FAMILY_DECIMAL_NUMBER: 'familyDecimalNumber',
    SUFFIX: 'suffix',
    CONFORMITY_STATEMENT: 'conformityStatement',
    ORDER_INDEX: 'orderIndex',
    SERIAL_NUMBER: 'serialNumber',
    GROUP_MAIN: 'groupMain',
    GROUP_SUB_MAIN: 'groupSubMain',
    TOTAL_LABOUR_INTENSITY: 'totalLabourIntensity',
    VALUE: 'value',
    OP_NAME: 'opName',
    OLD_VAL: 'oldVal',
    NEW_VAL: 'newVal',
    FINAL_VAL: 'finalVal',
    MSG: 'msg',
    PRODUCT_DEC_NUMBER: 'productDecNumber',
    PRODUCT_ID: 'productId',
    PAYMENT_RATE: 'paymentRate',
    LABOUR_INTENSITY: 'labourIntensity',
    SEND_TO_WAREHOUSE_DATE: 'sendToWarehouseDate',
    SEND_TO_PRODUCTION_DATE: 'sendToProductionDate',
    ALLOTMENT_SHIPPED_AMOUNT: 'allotmentShippedAmount',
    SHIPMENT_DATE: 'shipmentDate',
    PZ_COPY_DATE: 'pzCopyDate',
    ACCEPT_TYPE_CODE: 'acceptTypeCode',
    SPECIAL_TEST_TYPE_CODE: 'specialTestTypeCode',
    PLAN_NAME: 'planName',
    PLAN_START_DATE: 'planStartDate',
    PLAN_COMMENT: 'planComment',
    REPORT_NAME: 'reportName',
    REPORT_START_DATE: 'reportStartDate',
    REPORT_COMMENT: 'reportComment',
    LOCATION: 'location',
    TOTAL_AMOUNT: 'totalAmount',
    NOTE: 'note',
    RESIDUE_RESERVE_CONTRACT: 'residueReserveContract',
    RESIDUE_RESERVE: 'residueReserve',
    IN_STRUCT_RESERVE: 'inStructReserve',
    PRETENDERS: 'pretenders',
    FOR_CONTRACT: 'forContract',
    RESERVE_CONTRACT: 'reserveContract',
    RESERVE: 'reserve',
    TOTAL: 'total',
    LAUNCH_IN_STRUCT_OTHER: 'launchInStructOther',
    TOTAL_BEFORE_USED_RESERVE: 'totalBeforeUsedReserve',
    USED_RESERVE_CONTRACT: 'usedReserveContract',
    IN_STRUCT_USED_RESERVE: 'inStructUsedReserve',
    USED_RESERVE_ASSEMBLE: 'usedReserveAssemble',
    TOTAL_USED_RESERVE: 'totalUsedReserve',
    TOTAL_AFTER_USED_RESERVE: 'totalAfterUsedReserve',
    LABEL: 'label',
    EMPLOYEE_POSITION: 'employeePosition',
    FULL_NAME: 'fullName',
    ACCEPT_DATE: 'acceptDate',
    GIVE_USER: 'giveUser',
    ACCEPT_USER: 'acceptUser',
    CELL: 'cell',
    PRODUCT: 'product',
    PRODUCT_TYPE: 'productType',
    CONTRACT: 'contract',
    PRESENTATION: 'presentation',
    REG_DATE: 'regDate',
    STATEMENT: 'statement',
    LETTER: 'letter',
    STORAGE_PLACE: 'storagePlace',
    PACKED: 'packed',
    PAYER: 'payer',
    CONSIGNEE: 'consignee',
    VAT: 'vat',
    TOTAL_WO_VAT: 'totalWoVat',
    TOTAL_VAT: 'totalVat',
    PERMIT_USER: 'permitUser',
    ACCOUNTANT_USER: 'accountantUser',
    TRANSMITTAL_LETTER: 'transmittalLetter',
    LETTER_OF_ATTORNEY: 'letterOfAttorney',
    RECEIVER: 'receiver',
    RECEIVER_USER: 'receiverUser',
    EXTERNAL_NUMBER: 'externalNumber',
    READY: 'ready',
    SHIPPED: 'shipped',
    INTERNAL_WAYBILL: 'internalWaybill',
    CONDITIONAL_NAME: 'conditionalName',
    TAG: 'tag',
    NOTICE: 'notice',
    PLACE: 'place',
    TECHNICAL_CONTROL_DATE: 'technicalControlDate',
    WRAPPING_DATE: 'wrappingDate',
    INTER_WAREHOUSE_WAYBILL: 'interWarehouseWaybill',
    PRODUCTION_FINISH_DATE: 'productionFinishDate',
    SIGN_DATE: 'signDate',
    USER: 'user',
    INVOICE_DATE: 'invoiceDate',
    PAYER_NAME: 'payerName',
    ACCOUNT_NUMBER: 'accountNumber',
    ADVANCE_INVOICE_NUMBER: 'advanceInvoiceNumber',
    ADVANCE_INVOICE_DATE: 'advanceInvoiceDate',
    TEXT: 'text',
    MODEL: 'model',
    SIGN: 'sign',
    NOTICE_DATE: 'noticeDate',
    TECH_CONTROLLED: 'techControlled',
    SELECTED_ID: 'selectedId',
    SYMBOL: 'symbol',
    AREA_CODE: 'areaCode',
    WORK_TYPE: 'workType',
    LABOR_PROTECTION_INSTRUCTION: 'laborProtectionInstruction',
    EQUIPMENT: 'equipment',
    CONTENT: 'content',
    MODE: 'mode',
    TECHNOLOGICAL_TOOL: 'technologicalTool',
    OPERATION_MATERIAL: 'operationMaterial',
    VALIDITY_DATE: 'validityDate',
    TRANSFER_DATE: 'transferDate',
    LOT_GROUP_NUMBER: 'lotGroupNumber',
    POSITION: 'position',
    CATEGORY: 'category',
    PRODUCER: 'producer',
    SUBSTITUTE_COMPONENT: 'substituteComponent',
    MARK: 'mark',
    QUANTITY: 'quantity',
    DESIGNATION: 'designation',
    FIRMWARE: 'firmware',
    GIVEN_RAW_MATERIAL: 'givenRawMaterial',
    PRODUCERS: 'producers',
    BOM_ID: 'bomId',
    FIRST_DATE: 'firstDate',
    LAST_DATE: 'lastDate',
    BECAME_STANDART: 'becameStandart',
    BECAME_PRICE: 'becamePrice',
    WAS_STANDART: 'wasStandart',
    WAS_PRICE: 'wasPrice',
    ABSOLUTE_WITH_PACK: 'absoluteWPack',
    RELATIVE_WITH_PACK: 'relativeWPack',
    SERIAL: 'serial',
    DATE_FROM: 'dateFrom',
    DATE_TO: 'dateTo',
    MULTI: 'multi',
    SHORT_NAME: 'shortName',
    KOID: 'koid',
    KSHT: 'ksht',
    TPZ: 'tpz',
    TSHT: 'tsht',
    LABOUR_VALUE: 'labourValue',
    CHIEF_ID: 'chiefId'
};

// Некоторые константы для табулятора
const TABR_SORT_ID_DESC = [{ column: TABR_FIELD.ID, dir: SORT_DIR_DESC }];
const TABR_COL_ID = { field: TABR_FIELD.ID, visible: false };
const TABR_COL_REMOTE_ROW_NUM = {
    title: '',
    resizable: false,
    headerSort: false,
    headerHozAlign: 'center',
    hozAlign: 'center',
    frozen: true,
    width: 80,
    formatter: 'remoteRowNum'
};
const TABR_COL_LOCAL_ROW_NUM = {
    title: '',
    resizable: false,
    headerSort: false,
    headerHozAlign: 'center',
    hozAlign: 'center',
    frozen: true,
    width: 80,
    formatter: 'rownum'
};
const TABR_PAGE_SIZE = 50;
const TABR_MAX_PAGE_SIZE = TABR_PAGE_SIZE * 4;
// Селекторы табулятора
const TABR_SELECTOR_TABLE_HOLDER = 'div.tabulator-tableHolder';
// Вспомогательные класс табулятора
const TABR_CLASS_ROW_TOGGLE = 'tabulator-row-toggle'
const TABR_CLASS_ROW_TOGGLE_BUTTON = 'tabulator-row-toggle-button'
const TABR_CLASS_ROW_TOGGLE_EXPAND = 'tabulator-row-toggle-expand'
const TABR_CLASS_ROW_TOGGLE_COLLAPSE = 'tabulator-row-toggle-collapse'
const TABR_CLASS_ROW_TOGGLE_HOLDER = 'tabulator-row-toggle-holder'
// Атрибуты табуляторя для запроса
const TABR_REQ_ATTR_PAGE = 'page';
const TABR_REQ_ATTR_SIZE = 'size';
const TABR_REQ_ATTR_FIELD = 'sorters[0][field]';
const TABR_REQ_ATTR_DIR = 'sorters[0][dir]';
const TABR_REQ_ATTR_FILTER_DATA = 'filterData';
// Атрибуты табулятора для работы с URL
const TABR_URL_ATTR_PAGE = 'tabrPage';
const TABR_URL_ATTR_SIZE = 'tabrSize';
const TABR_URL_ATTR_SORT_FIELD = 'tabrSortField';
const TABR_URL_ATTR_SORT_DIR = 'tabrSortDir';
const TABR_URL_ATTR_FILTER_DATA = 'tabrFilterData';